jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('{0}_python_{1}', image, pythonVersion) }}
        pool:
          vmImage: ${{ image }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true

          - script: sudo apt-get install --force-yes -y make libudev-dev g++ libsdl2-dev
            displayName: 'Install libs'

          - script: python -m pip install --upgrade pip setuptools wheel build
            displayName: 'Install tools'

          - script: python -m pip install pycparser cffi
            displayName: 'Install build requirements'

          - script: python -m build
            displayName: 'build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'dist'
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: "$(Agent.JobName)_x64"
              PublishLocation: 'Container'