jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true
          - script: python -m pip install --upgrade pip setuptools wheel requests
            displayName: 'Install tools'

          - script: python -m pip install pycparser cffi pyMSVC>=0.5.1
            displayName: 'Install build requirements'

          - script: python setup.py build
            displayName: 'build'
