jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true

          - script: brew install sdl2

            displayName: 'Install libs'

          - script: python -m pip install --upgrade pip setuptools wheel build
            displayName: 'Install tools'

          - script: python -m pip install pycparser cffi
            displayName: 'Install build requirements'

          - script: python setup.py bdist_wheel
            displayName: 'build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'dist'
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: "artifact_$(Agent.OS)_$(Agent.JobName)_$(python.architecture)"
              PublishLocation: 'Container'